# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "TWO FASTLANE"
description: > # this means to ignore newlines until "email:"
   Android, React-native, swift, AWS, Programming

email: kms860226@gmail.com
#blog logo
logo: "/assets/images/logo1.png"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/background.jpg"

name: 'Ninja86'
author: 'Ninja86'
author_image: "/assets/images/profile.jpg"

paginate:	5

url: "https://Ninja86.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@luxo_l8'

#fill in disqus shortname to use disqus
disqus: ninja86-blog

google_analytics: UA-91026007-2

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/luxo_l8
    desc: twitter
    share_url: 
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/wrotebyming
    desc: Facebook
    share_url: 
    share_title: 
    share_link: 

  - icon:	github
    url:	https://github.com/Ninja86
    desc:	Github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

markdown: kramdown
